# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: mvn clean install
  displayName: 'Build'

- script: |
    mvn test
    mvn verify
  displayName: 'Run a multi-line script'
# Publish Test Results to Azure Pipelines/TFS
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo' # Options: cobertura, jaCoCo
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco-both/index.html'
    #reportDirectory: # Optional
    #additionalCodeCoverageFiles: # Optional
    #failIfCoverageEmpty: false # Optional
